### PR TITLE
To fix mirrored images (y axis)

### PR DESCRIPTION
**Pull request by philipguedes**
Original:
image

One of the cubemap faces:
image

### CODE REVIEW

**Comment by thomcc** [comment]
Ah, yeah, that's not so great.

Unfortunately, this will break code currently using this library, so I'm reluctant to merge it as is. Can you address your issue via changing how you generate texture coords in your shader?

If not, maybe there should some options passed into the function. Maybe flipX and flipY per face? IDK.

**Comment by philipguedes** [comment]
Oh, I see. 

I'll try to make some more changes in order to avoid code breaking, but I believe that is not so hard for someone to flipY/mirrorY each face after they use the algorithm.

The problem is that your commented code about the faces (right, left, top, ...) will still be giving the wrong idea to people. Besides, I'm not sure if you can ensure consistency when someone tries the way back (from cubemap to equirect).

Btw, Is this a known issue?

**Comment by thomcc** [comment]
It's not a known issue (honestly, I ended up not needing this for the project I wrote it for, so maybe it is known to users, which... well, there are probably a couple).

I think it is a bug, but fixing it would be a breaking change, so... are all the other faces correct? I guess I'm willing to merge this (and bump the major version number) if it will make everything else correct, but I don't want to do that sort of thing often.

Worth noting that this might have been (probably was) introduced by #1, but when I got that PR I was very busy in my life and didn't really have time to think about it beyond "yes okay fine".

Since then I've had evidence more people have used this library so I'm not willing to change something like that without a major version bump (which I should have done then also).

**Comment by thomcc** [comment]
Fixed in the latest commit by a different method. Update to 2.0.0 for fix, users who want the old behavior can get it via an optional parameter.

**Pull request closed without merging**
